--- 
document: 
  description: "Il presente documento rappresenta l’Allegato B alle «Linee guida per l'effettuazione dei pagamenti a favore delle pubbliche amministrazioni e dei gestori di pubblici servizi» e deve essere utilizzato in combinazione con il documento «Specifiche attuative dei codici identificativi di versamento, riversamento e rendicontazione» (Allegato A), nonché con le stesse Linee guida."
  name: "Specifiche attuative del nodo dei pagamenti SPC"
  tags:
    - specifiche
    - pagoPA
    - SANP
    - SACI
